Repository DevelopLife/reviewtwits_backend, pull requests merged in 2023-04, with the labels that each got.

#123 [feature] 리뷰 SNS 작성 및 피드 관련 기능 모두 추가
  src/main/java/com/developlife/reviewtwits/controller/ShoppingMallReviewController.java
  src/main/java/com/developlife/reviewtwits/controller/SnsReviewController.java
  src/main/java/com/developlife/reviewtwits/entity/Comment.java
  src/main/java/com/developlife/reviewtwits/entity/Reaction.java
  src/main/java/com/developlife/reviewtwits/entity/Review.java
  src/main/java/com/developlife/reviewtwits/entity/User.java
  src/main/java/com/developlife/reviewtwits/exception/review/CommentNotFoundException.java
  src/main/java/com/developlife/reviewtwits/exception/review/ReactionNotFoundException.java
  src/main/java/com/developlife/reviewtwits/exception/review/ReviewNotFoundException.java
  src/main/java/com/developlife/reviewtwits/handler/ReviewExceptionHandler.java
  src/main/java/com/developlife/reviewtwits/mapper/ReviewMapper.java
  src/main/java/com/developlife/reviewtwits/message/annotation/review/ValidReaction.java
  src/main/java/com/developlife/reviewtwits/message/request/review/SnsCommentWriteRequest.java
  src/main/java/com/developlife/reviewtwits/message/request/review/SnsReviewChangeRequest.java
  src/main/java/com/developlife/reviewtwits/message/request/review/SnsReviewWriteRequest.java
  src/main/java/com/developlife/reviewtwits/message/response/review/CommentResponse.java
  src/main/java/com/developlife/reviewtwits/message/response/review/DetailReviewResponse.java
  src/main/java/com/developlife/reviewtwits/message/response/review/DetailShoppingMallReviewResponse.java
  src/main/java/com/developlife/reviewtwits/message/response/review/DetailSnsReviewResponse.java
  src/main/java/com/developlife/reviewtwits/message/response/review/ReactionResponse.java
  src/main/java/com/developlife/reviewtwits/message/validator/review/ReactionValidator.java
  src/main/java/com/developlife/reviewtwits/repository/CommentRepository.java
  src/main/java/com/developlife/reviewtwits/repository/ReactionRepository.java
  src/main/java/com/developlife/reviewtwits/repository/ReviewRepository.java
  src/main/java/com/developlife/reviewtwits/service/ShoppingMallReviewService.java
  src/main/java/com/developlife/reviewtwits/service/SnsReviewService.java
  src/main/java/com/developlife/reviewtwits/type/ReactionType.java
  src/test/java/com/developlife/reviewtwits/review/ShoppingMallReviewApiTest.java
  src/test/java/com/developlife/reviewtwits/review/ShoppingMallReviewDocument.java
  src/test/java/com/developlife/reviewtwits/review/ShoppingMallReviewSteps.java
  src/test/java/com/developlife/reviewtwits/review/SnsReviewApiTest.java
  src/test/java/com/developlife/reviewtwits/review/SnsReviewDocument.java
  src/test/java/com/developlife/reviewtwits/review/SnsReviewSteps.java
  src/test/java/com/developlife/reviewtwits/user/UserApiTest.java
  src/test/java/com/developlife/reviewtwits/user/UserSteps.java
  src/test/resources/application.properties
Labels: feat, test

#141 [FIX] multipart() 한글 깨짐 문제 해결 및 해결 관련 method 제작
  src/test/java/com/developlife/reviewtwits/review/SnsReviewApiTest.java
  src/test/java/com/developlife/reviewtwits/review/SnsReviewSteps.java
Labels: test

#143 #132 [feature] SNS 리뷰 수정/삭제 테스트 케이스 추가 및 북마크 관련 기능 추가
  src/main/java/com/developlife/reviewtwits/config/security/WebSecurityConfig.java
  src/main/java/com/developlife/reviewtwits/controller/SnsReviewController.java
  src/main/java/com/developlife/reviewtwits/entity/ReviewScrap.java
  src/main/java/com/developlife/reviewtwits/exception/review/ReviewScrapNotAddedException.java
  src/main/java/com/developlife/reviewtwits/handler/ReviewExceptionHandler.java
  src/main/java/com/developlife/reviewtwits/mapper/ReviewMapper.java
  src/main/java/com/developlife/reviewtwits/message/annotation/review/DeleteFileName.java
  src/main/java/com/developlife/reviewtwits/message/request/review/ShoppingMallReviewChangeRequest.java
  src/main/java/com/developlife/reviewtwits/message/request/review/SnsReviewChangeRequest.java
  src/main/java/com/developlife/reviewtwits/message/response/review/DetailSnsReviewResponse.java
  src/main/java/com/developlife/reviewtwits/message/validator/review/DeleteFileNameValidator.java
  src/main/java/com/developlife/reviewtwits/repository/ReviewScrapRepository.java
  src/main/java/com/developlife/reviewtwits/service/SnsReviewService.java
  src/main/java/com/developlife/reviewtwits/type/FileReferenceType.java
  src/test/java/com/developlife/reviewtwits/review/SnsReviewApiTest.java
  src/test/java/com/developlife/reviewtwits/review/SnsReviewDocument.java
  src/test/java/com/developlife/reviewtwits/review/SnsReviewSteps.java
Labels: feat, test

#152 [feature] 유저 개인 프로필 정보 요청하는 기능 추가
  src/main/java/com/developlife/reviewtwits/controller/SnsController.java
  src/main/java/com/developlife/reviewtwits/entity/User.java
  src/main/java/com/developlife/reviewtwits/handler/UserExceptionHandler.java
  src/main/java/com/developlife/reviewtwits/mapper/ReviewMapper.java
  src/main/java/com/developlife/reviewtwits/mapper/UserMapper.java
  src/main/java/com/developlife/reviewtwits/message/response/user/UserInfoResponse.java
  src/main/java/com/developlife/reviewtwits/repository/ReviewRepository.java
  src/main/java/com/developlife/reviewtwits/repository/follow/FollowRepository.java
  src/main/java/com/developlife/reviewtwits/service/FileStoreService.java
  src/main/java/com/developlife/reviewtwits/service/SnsService.java
  src/main/java/com/developlife/reviewtwits/service/user/UserService.java
  src/test/java/com/developlife/reviewtwits/review/ShoppingMallReviewDocument.java
  src/test/java/com/developlife/reviewtwits/review/SnsReviewDocument.java
  src/test/java/com/developlife/reviewtwits/sns/SnsApiTest.java
  src/test/java/com/developlife/reviewtwits/sns/SnsDocument.java
  src/test/java/com/developlife/reviewtwits/sns/SnsSteps.java
  src/test/java/com/developlife/reviewtwits/user/UserDocument.java
  src/test/java/com/developlife/reviewtwits/user/UserSteps.java
Labels: feat, test

#153 [feature] 개인페이지 리뷰정보 조회 기능 추가
  src/main/java/com/developlife/reviewtwits/controller/SnsController.java
  src/main/java/com/developlife/reviewtwits/entity/Review.java
  src/main/java/com/developlife/reviewtwits/mapper/ReviewMapper.java
  src/main/java/com/developlife/reviewtwits/message/response/sns/SnsReviewResponse.java
  src/main/java/com/developlife/reviewtwits/service/SnsReviewService.java
  src/main/java/com/developlife/reviewtwits/service/SnsService.java
  src/test/java/com/developlife/reviewtwits/review/SnsReviewSteps.java
  src/test/java/com/developlife/reviewtwits/sns/SnsApiTest.java
  src/test/java/com/developlife/reviewtwits/sns/SnsDocument.java
Labels: feat, test

#154 [feature] 댓글 좋아요 기능 추가
  src/main/java/com/developlife/reviewtwits/config/security/WebSecurityConfig.java
  src/main/java/com/developlife/reviewtwits/controller/SnsReviewController.java
  src/main/java/com/developlife/reviewtwits/entity/Comment.java
  src/main/java/com/developlife/reviewtwits/entity/CommentLike.java
  src/main/java/com/developlife/reviewtwits/exception/review/CommentLikeAlreadyProcessedException.java
  src/main/java/com/developlife/reviewtwits/handler/ReviewExceptionHandler.java
  src/main/java/com/developlife/reviewtwits/repository/CommentLikeRepository.java
  src/main/java/com/developlife/reviewtwits/service/SnsReviewService.java
  src/main/java/com/developlife/reviewtwits/service/SnsService.java
  src/test/java/com/developlife/reviewtwits/review/SnsReviewApiTest.java
  src/test/java/com/developlife/reviewtwits/review/SnsReviewDocument.java
Labels: feat, test

#172 [REFACTOR] 팔로우/언팔로우 파라미터를 계정에서 닉네임으로 변경
  src/main/java/com/developlife/reviewtwits/controller/SnsController.java
  src/main/java/com/developlife/reviewtwits/message/request/sns/FollowRequest.java
  src/main/java/com/developlife/reviewtwits/service/SnsService.java
  src/test/java/com/developlife/reviewtwits/sns/SnsApiTest.java
  src/test/java/com/developlife/reviewtwits/sns/SnsDocument.java
  src/test/java/com/developlife/reviewtwits/sns/SnsSteps.java
Labels: non-review

#174 [FIX] 테스트 고쳐야 하는거 빼먹은부분 다시 수정
  src/test/java/com/developlife/reviewtwits/sns/SnsApiTest.java
Labels: non-review

#175 [feature] 통계 작성 API 사전작업 구현 추가
  src/main/java/com/developlife/reviewtwits/entity/StatInfo.java
  src/main/java/com/developlife/reviewtwits/message/annotation/project/ChartPeriod.java
  src/main/java/com/developlife/reviewtwits/message/validator/project/ChartPeriodInputValidator.java
  src/main/java/com/developlife/reviewtwits/repository/StatInfoRepository.java
  src/main/java/com/developlife/reviewtwits/type/project/ChartPeriodUnit.java
  src/main/java/com/developlife/reviewtwits/type/project/Device.java
  src/main/java/com/developlife/reviewtwits/type/project/Inflow.java
Labels: feat

#177 [refactor] 인증/인가 에러 코드를 401, 403으로 분리 및 해당 기능 테스트 케이스 보강
  src/main/java/com/developlife/reviewtwits/config/security/WebSecurityConfig.java
  src/main/java/com/developlife/reviewtwits/entity/StatInfo.java
  src/main/java/com/developlife/reviewtwits/handler/ReviewExceptionHandler.java
  src/main/java/com/developlife/reviewtwits/message/annotation/project/ChartPeriod.java
  src/main/java/com/developlife/reviewtwits/service/ProjectService.java
  src/main/java/com/developlife/reviewtwits/service/SnsService.java
  src/test/java/com/developlife/reviewtwits/review/ShoppingMallReviewApiTest.java
  src/test/java/com/developlife/reviewtwits/review/SnsReviewApiTest.java
  src/test/java/com/developlife/reviewtwits/sns/SnsApiTest.java
  src/test/java/com/developlife/reviewtwits/user/UserApiTest.java
  src/test/java/com/developlife/reviewtwits/user/UserSteps.java
Labels: feat, test

#179 #157 [FEAT] 서버에 통계정보 전달 기능 코드 및 테스트 전체 보강
  src/main/java/com/developlife/reviewtwits/controller/StatController.java
  src/main/java/com/developlife/reviewtwits/mapper/StatMapper.java
  src/main/java/com/developlife/reviewtwits/message/annotation/statistics/HttpURL.java
  src/main/java/com/developlife/reviewtwits/message/request/StatMessageRequest.java
  src/main/java/com/developlife/reviewtwits/message/validator/statistics/HttpURLValidator.java
  src/test/java/com/developlife/reviewtwits/statistics/StatApiTest.java
  src/test/java/com/developlife/reviewtwits/statistics/StatDocument.java
  src/test/java/com/developlife/reviewtwits/statistics/StatInfoSteps.java
Labels: test, non-review

#180 [feature] 일간 통계정보 및 최근 방문자 수를 반환하는 API 기능 추가
  build.gradle
  src/main/java/com/developlife/reviewtwits/controller/ProjectController.java
  src/main/java/com/developlife/reviewtwits/handler/ProjectExceptionHandler.java
  src/main/java/com/developlife/reviewtwits/service/ProjectService.java
  src/main/java/com/developlife/reviewtwits/type/project/ChartPeriodUnit.java
  src/test/java/com/developlife/reviewtwits/project/ProjectApiTest.java
  src/test/java/com/developlife/reviewtwits/project/ProjectDocument.java
  src/test/java/com/developlife/reviewtwits/project/ProjectSteps.java
  src/test/java/com/developlife/reviewtwits/statistics/StatApiTest.java
Labels: feat, test

#182 #157 [DOCS] document 오타 수정
  src/test/java/com/developlife/reviewtwits/project/ProjectApiTest.java
Labels: non-review

#183 [FIX] 리뷰 피드에 profileImageUrl 붙지 않는 문제 긴급수정
  src/main/java/com/developlife/reviewtwits/mapper/ReviewMapper.java
Labels: non-review

#184 [FEAT] 피드에서 리뷰 리스트의 마지막에 도달했을 때 204 를 보내주는 기능 추가
  src/main/java/com/developlife/reviewtwits/exception/review/ReviewListEmptyException.java
  src/main/java/com/developlife/reviewtwits/handler/ReviewExceptionHandler.java
  src/main/java/com/developlife/reviewtwits/service/SnsReviewService.java
  src/test/java/com/developlife/reviewtwits/review/SnsReviewApiTest.java
Labels: non-review

#185 [DOCS] 리뷰 마지막에 요청 보낼때 204 보낸다는 부분 문서 명시
  src/test/java/com/developlife/reviewtwits/review/SnsReviewApiTest.java
Labels: non-review

#186 [FIX] cors mapping fix 시도(https://reviewtwits.shop 추가)
  src/main/java/com/developlife/reviewtwits/config/WebMvcConfig.java
Labels: non-review

#187 [FIX] 사진 두개 중복되어서 프론트에게로 나가는 이슈 해결 시도
  src/main/java/com/developlife/reviewtwits/repository/review/ReviewMappingDTO.java
  src/main/java/com/developlife/reviewtwits/repository/review/ReviewMappingRepositoryImpl.java
Labels: non-review

#188 [FIX] CORS 문제 해결 시도
  src/main/java/com/developlife/reviewtwits/config/WebMvcConfig.java
Labels: non-review

#189 [CHORE] 슬래시 누락이슈 교정(UserController)
  src/main/java/com/developlife/reviewtwits/controller/UserController.java
Labels: non-review

#190 [FIX] CORS 해결을 위한 WebSecurityConfig 에 추가
  src/main/java/com/developlife/reviewtwits/config/security/WebSecurityConfig.java
Labels: non-review

#192 [refactor] 팔로잉, 팔로우 목록을 pagination 및 유저 프로필정보 받을 때 팔로우여부 알 수 있게 refactor
  src/main/java/com/developlife/reviewtwits/controller/SnsController.java
  src/main/java/com/developlife/reviewtwits/mapper/UserMapper.java
  src/main/java/com/developlife/reviewtwits/message/response/user/UserInfoResponse.java
  src/main/java/com/developlife/reviewtwits/repository/follow/FollowCustomRepository.java
  src/main/java/com/developlife/reviewtwits/repository/follow/FollowCustomRepositoryImpl.java
  src/main/java/com/developlife/reviewtwits/service/SnsService.java
  src/test/java/com/developlife/reviewtwits/review/ShoppingMallReviewDocument.java
  src/test/java/com/developlife/reviewtwits/review/SnsReviewDocument.java
  src/test/java/com/developlife/reviewtwits/sns/SnsApiTest.java
  src/test/java/com/developlife/reviewtwits/sns/SnsDocument.java
  src/test/java/com/developlife/reviewtwits/sns/SnsSteps.java
  src/test/java/com/developlife/reviewtwits/statistics/StatDocument.java
  src/test/java/com/developlife/reviewtwits/user/UserDocument.java
Labels: non-review

#194 [FIX] localhost 잡아내지 못하는 url pattern 코드 수정
  src/main/java/com/developlife/reviewtwits/message/request/review/ShoppingMallReviewWriteRequest.java
  src/main/java/com/developlife/reviewtwits/message/validator/statistics/HttpURLValidator.java
Labels: non-review
